In [1]:
import pandas as pd
import numpy as np

In [3]:
incidents = pd.read_csv('/Users/kamilw/Desktop/Moje/PythonLearing/Pandas_Udemy/course-files/Canadian Railway Crossing Incidents.csv')

In [4]:
incidents.head(10)

,Region,EventType,Public automated,Public passive,Private,Farm
0,Newfoundland,Accidents,0,0,0,0
1,Newfoundland,Fatalities,0,0,0,0
2,Newfoundland,Serious injuries,0,0,0,0
3,Nova Scotia,Accidents,1,0,0,0
4,Nova Scotia,Fatalities,0,0,0,0
5,Nova Scotia,Serious injuries,0,0,0,0
6,New Brunswick,Accidents,0,0,0,0
7,New Brunswick,Fatalities,0,0,0,0
8,New Brunswick,Serious injuries,0,0,0,0
9,Quebec,Accidents,4,0,1,0

In [5]:
# ustawiamy nowy indeks
incidents.set_index('Region').head()

,EventType,Public automated,Public passive,Private,Farm
Region,,,,,
Newfoundland,Accidents,0,0,0,0
Newfoundland,Fatalities,0,0,0,0
Newfoundland,Serious injuries,0,0,0,0
Nova Scotia,Accidents,1,0,0,0
Nova Scotia,Fatalities,0,0,0,0

In [6]:
# wyżej jest nieunikalny indeks i nie można konkretnie wskazać wiersza

In [7]:
# ten indeks też jest nieunikalny
incidents.set_index('EventType').head()

,Region,Public automated,Public passive,Private,Farm
EventType,,,,,
Accidents,Newfoundland,0,0,0,0
Fatalities,Newfoundland,0,0,0,0
Serious injuries,Newfoundland,0,0,0,0
Accidents,Nova Scotia,1,0,0,0
Fatalities,Nova Scotia,0,0,0,0

In [8]:
# indeks jako dwie kolumny
incidents.set_index(['Region','EventType']).head()
# posortowane

                               Public automated  Public passive  Private  Farm
Region       EventType
Newfoundland Accidents                        0               0        0     0
             Fatalities                       0               0        0     0
             Serious injuries                 0               0        0     0
Nova Scotia  Accidents                        1               0        0     0
             Fatalities                       0               0        0     0

In [11]:
incidents.set_index(keys=['EventType','Region'],inplace=True)

In [12]:
incidents.head()
# nieposortowane

                               Public automated  Public passive  Private  Farm
EventType        Region
Accidents        Newfoundland                 0               0        0     0
Fatalities       Newfoundland                 0               0        0     0
Serious injuries Newfoundland                 0               0        0     0
Accidents        Nova Scotia                  1               0        0     0
Fatalities       Nova Scotia                  0               0        0     0

In [13]:
# sortowanie
incidents.sort_index(inplace=True)

In [15]:
incidents.head(10)

                                 Public automated  Public passive  Private  \
EventType Region
Accidents Alberta                               3               7        2
          British Columbia                      4               1        0
          Manitoba                              1               3        0
          New Brunswick                         0               0        0
          Newfoundland                          0               0        0
          Northwest Territories                 0               0        0
          Nova Scotia                           1               0        0
          Ontario                               7               0        2
          Quebec                                4               0        1
          Saskatchewan                          1               3        0

                                 Farm
EventType Region
Accidents Alberta                   0
          British Columbia          0
          Manitoba                  2
          New Brunswick             0
          Newfoundland              0
          Northwest Territories     0
          Nova Scotia               0
          Ontario                   0
          Quebec                    0
          Saskatchewan              0

In [16]:
# sortowanie oddzielnie jednej i drugiej kolumnie indeksu
incidents.sort_index(ascending=[True,False],inplace=True)

In [17]:
incidents.head()

                                 Public automated  Public passive  Private  \
EventType Region
Accidents Saskatchewan                          1               3        0
          Quebec                                4               0        1
          Ontario                               7               0        2
          Nova Scotia                           1               0        0
          Northwest Territories                 0               0        0

                                 Farm
EventType Region
Accidents Saskatchewan              0
          Quebec                    0
          Ontario                   0
          Nova Scotia               0
          Northwest Territories     0

In [18]:
# multiindex
# df.set_index(["col1","col2"])
# df.sort_index()
# df.sort_index(keys=["col1","col2"],ascending=[True,False])